# Restrict pre-commit checks to CI configuration files
repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: [--line-length=100]
        files: ^$
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: [--fix]
        files: ^$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        files: ^\.github/(dependabot\.yml|workflows/.*\.yml)$
      - id: trailing-whitespace
        files: ^\.github/(dependabot\.yml|workflows/.*\.yml)$
