line-length = 88
target-version = "py311"
select = ["E","F","I","UP","B","C4","SIM","ARG"]
ignore = ["E203"]
fix = true

[per-file-ignores]
"tests/*" = ["S101", "B017"]

[isort]
known-first-party = ["src", "cortex", "mcp_server"]
