#!/usr/bin/env python3
"""Check pattern matching between templates and plugin output"""

import re


def test_pattern_matching():
    print('Testing pattern matches between templates and plugin output...')
    
    # Patterns from autogen templates
    web_scraper_patterns = [
        re.compile(r'^src/abilities/.*web_scraper', re.I),
        re.compile(r'^tests/abilities/.*web_scraper', re.I),
    ]
    
    # Paths generated by our native plugin
    generated_paths = [
        'src/capabilities/web_scraper.py',
        'tests/capabilities/test_web_scraper.py', 
        'docs/capabilities/web_scraper.md'
    ]
    
    print('\nPattern matching results:')
    for i, pattern in enumerate(web_scraper_patterns):
        print(f'\nPattern {i+1}: {pattern.pattern}')
        for path in generated_paths:
            match = pattern.search(path)
            status = "✓ MATCH" if match else "✗ NO MATCH"
            print(f'  {path}: {status}')
    
    print('\n--- ISSUE IDENTIFIED ---')
    print('The templates expect paths under src/abilities/ and tests/abilities/')
    print('But our plugin generates paths under src/capabilities/ and tests/capabilities/')
    print('\nSolution: Update plugin to generate correct paths or update templates')


if __name__ == "__main__":
    test_pattern_matching()