#!/usr/bin/env python3
"""
API Client - Generated by Native DeepCode
Requirements: Build a typed API client *ability*:
- Declarative endpoints spec; retries/backoff; timeout; auth hooks;
  tests; docs; Makefile target.
- No secrets in code; safety enforced.
Task:
I need to implement a RESTful API client for a social media platform.
This should include authentication, rate limiting, error handling, and methods for:
- Getting user profiles
- Posting messages
- Following/unfollowing users
- Retrieving timeline feeds
- Uploading media


"""

import json
import logging
from typing import Any
from urllib.parse import urljoin

import requests

logger = logging.getLogger(__name__)


class APIClient:
    """REST API client with common patterns"""

    def __init__(self, base_url: str, api_key: str | None = None):
        self.base_url = base_url.rstrip("/")
        self.session = requests.Session()

        # Set up authentication if API key provided
        if api_key:
            self.session.headers.update({"Authorization": f"Bearer {api_key}"})

        # Common headers
        self.session.headers.update(
            {
                "Content-Type": "application/json",
                "Accept": "application/json",
                "User-Agent": "APIClient/1.0",
            }
        )

    def _make_request(
        self,
        method: str,
        endpoint: str,
        data: dict[str, Any] | None = None,
        params: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Make HTTP request with error handling"""
        url = urljoin(f"{self.base_url}/", endpoint.lstrip("/"))

        try:
            response = self.session.request(
                method=method, url=url, json=data, params=params
            )
            response.raise_for_status()

            # Try to parse JSON response
            try:
                return response.json()
            except json.JSONDecodeError:
                return {"status": "success", "data": response.text}

        except requests.exceptions.RequestException as e:
            logger.error(f"API request failed: {e}")
            return {"error": str(e), "status": "failed"}

    def get(
        self, endpoint: str, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        """GET request"""
        return self._make_request("GET", endpoint, params=params)

    # Optional event bus integration for demos
    async def initialize(self, event_bus) -> bool:  # pragma: no cover
        """Wire to an event bus; subscribe to system_shutdown if available."""
        self.event_bus = event_bus
        try:
            if hasattr(event_bus, "subscribe"):
                await event_bus.subscribe(
                    "system_shutdown", getattr(self, "shutdown", lambda *_: None)
                )
        except Exception:
            pass
        return True

    def post(self, endpoint: str, data: dict[str, Any] | None = None) -> dict[str, Any]:
        """POST request"""
        return self._make_request("POST", endpoint, data=data)

    def put(self, endpoint: str, data: dict[str, Any] | None = None) -> dict[str, Any]:
        """PUT request"""
        return self._make_request("PUT", endpoint, data=data)

    def delete(self, endpoint: str) -> dict[str, Any]:
        """DELETE request"""
        return self._make_request("DELETE", endpoint)

    def paginate(self, endpoint: str, page_size: int = 50) -> list[dict[str, Any]]:
        """Handle paginated responses"""
        all_data = []
        page = 1

        while True:
            params = {"page": page, "limit": page_size}
            response = self.get(endpoint, params=params)

            if "error" in response:
                logger.error(f"Pagination failed: {response['error']}")
                break

            data = response.get("data", [])
            if not data:
                break

            all_data.extend(data)

            # Check if there are more pages
            if len(data) < page_size:
                break

            page += 1

        return all_data


def create_api_client(base_url: str, api_key: str | None = None) -> APIClient:
    """Factory function to create API client"""
    return APIClient(base_url, api_key)


if __name__ == "__main__":
    # Example usage
    client = create_api_client("https://api.example.com")

    # GET request
    users = client.get("/users")
    print(f"Users: {users}")

    # POST request
    new_user = client.post("/users", {"name": "John", "email": "john@example.com"})
    print(f"Created user: {new_user}")
