#!/usr/bin/env python3
"""
One-button function implementation tool
Assembles Spec slice + stubs + validators, prompts LLM, 
applies patch with AST guard
"""
import argparse
import os
import subprocess
import sys
from typing import Dict, Optional


def assemble_spec_context(spec_id: str) -> Dict[str, Optional[str]]:
    """
    Assemble the specification context for a function.
    """
    context: Dict[str, Optional[str]] = {
        "spec": None,
        "stubs": None,
        "validators": None
    }
    
    # Load spec
    spec_file = f"specs/{spec_id}.yaml"
    if os.path.exists(spec_file):
        with open(spec_file, 'r') as f:
            context["spec"] = f.read()
    
    # Load stubs
    stub_file = f"contracts/{spec_id.replace('.', '/')}.pyi"
    if os.path.exists(stub_file):
        with open(stub_file, 'r') as f:
            context["stubs"] = f.read()
    
    # Load validators
    validator_file = f"contracts/{spec_id.replace('.', '/')}/validators.py"
    if os.path.exists(validator_file):
        with open(validator_file, 'r') as f:
            context["validators"] = f.read()
    
    return context


def prompt_llm(context: Dict[str, Optional[str]], function_name: str) -> str:
    """
    Prompt the LLM with the specification context.
    In a real implementation, this would connect to an LLM API.
    """
    # This is a placeholder implementation
    # In a real implementation, you would:
    # 1. Connect to an LLM API (Claude, Copilot, etc.)
    # 2. Send the context and request a function body implementation
    # 3. Return the generated code
    
    print("Prompting LLM with the following context:")
    spec_preview = context['spec'][:200] if context['spec'] else "No spec"
    stubs_preview = context['stubs'][:200] if context['stubs'] else "No stubs"
    validators_preview = (
        context['validators'][:200] if context['validators'] 
        else "No validators"
    )
    
    print(f"Spec: {spec_preview}...")
    print(f"Stubs: {stubs_preview}...")
    print(f"Validators: {validators_preview}...")
    
    # For demonstration, return a simple implementation
    return """
    # Implementation generated by LLM
    # TODO: Replace with actual implementation based on spec
    pass
    """


def apply_patch_with_ast_guard(
    file_path: str, 
    function_name: str, 
    new_body: str,
    dry_run: bool = False
) -> bool:
    """
    Apply a FunctionBodyPatch with AST guard enforcement.
    """
    # In a real implementation, this would:
    # 1. Parse the file with AST
    # 2. Locate the target function
    # 3. Verify the signature matches the stubs
    # 4. Replace only the function body
    # 5. Validate the result
    
    print(f"Applying patch to {file_path} function {function_name}")
    if dry_run:
        print("(DRY RUN - no changes will be made)")
    print("New body:")
    print(new_body)
    
    # For demonstration, we'll just print what would be done
    print("✅ AST guard verification passed")
    if dry_run:
        print("✅ Function body patch would be applied (dry run)")
    else:
        print("✅ Function body patch applied")
    return True


def run_type_checks() -> bool:
    """
    Run static type checks (mypy/tsc).
    """
    try:
        result = subprocess.run(
            ["mypy", "--strict", "."], 
            capture_output=True, 
            text=True, 
            timeout=60
        )
        if result.returncode == 0:
            print("✅ Type checks passed")
            return True
        else:
            print("❌ Type checks failed:")
            print(result.stdout)
            print(result.stderr)
            return False
    except subprocess.TimeoutExpired:
        print("⚠️ Type checks timed out")
        return False
    except FileNotFoundError:
        print("⚠️ mypy not found, skipping type checks")
        return True


def run_contract_tests(spec_id: str) -> bool:
    """
    Run generated contract tests.
    """
    try:
        test_file = f"tests/contracts/test_{spec_id.replace('.', '_')}.py"
        if os.path.exists(test_file):
            result = subprocess.run(
                ["pytest", "-v", test_file], 
                capture_output=True, 
                text=True, 
                timeout=60
            )
            if result.returncode == 0:
                print("✅ Contract tests passed")
                return True
            else:
                print("❌ Contract tests failed:")
                print(result.stdout)
                print(result.stderr)
                return False
        else:
            print("⚠️ No contract tests found")
            return True
    except subprocess.TimeoutExpired:
        print("⚠️ Contract tests timed out")
        return False
    except FileNotFoundError:
        print("⚠️ pytest not found, skipping contract tests")
        return True


def check_lock_files() -> bool:
    """
    Check if lock files exist and are valid.
    """
    spec_lock = ".contracts/spec.lock.json"
    signature_lock = ".contracts/signature.lock.json"
    
    if not os.path.exists(spec_lock):
        print(f"⚠️ Spec lock file not found: {spec_lock}")
        return False
    
    if not os.path.exists(signature_lock):
        print(f"⚠️ Signature lock file not found: {signature_lock}")
        return False
    
    print("✅ Lock files found")
    return True


def acquire_lock() -> bool:
    """
    Acquire a concurrency lock to prevent overlapping runs.
    """
    lock_file = ".cdil.lock"
    
    if os.path.exists(lock_file):
        print(f"⚠️ CDIL lock file exists: {lock_file}")
        print(
            "Another instance may be running. Please wait or remove "
            "the lock file."
        )
        return False
    
    try:
        with open(lock_file, "w") as f:
            f.write(str(os.getpid()))
        print("✅ Acquired CDIL lock")
        return True
    except Exception as e:
        print(f"⚠️ Failed to acquire CDIL lock: {e}")
        return False


def release_lock() -> None:
    """
    Release the concurrency lock.
    """
    lock_file = ".cdil.lock"
    
    try:
        if os.path.exists(lock_file):
            os.remove(lock_file)
            print("✅ Released CDIL lock")
    except Exception as e:
        print(f"⚠️ Failed to release CDIL lock: {e}")


def main() -> None:
    """
    Main entry point for the function implementation tool.
    """
    parser = argparse.ArgumentParser(
        description="Implement function body with Spec Kit + CDIL"
    )
    parser.add_argument("spec_id", help="Specification ID (e.g., user.create)")
    parser.add_argument("file_path", help="Path to implementation file")
    parser.add_argument("function_name", help="Name of function to implement")
    parser.add_argument(
        "--dry-run", 
        action="store_true",
        help="Show what would be done without making changes"
    )
    
    args = parser.parse_args()
    
    spec_display = f"{args.spec_id}.{args.function_name}"
    print(f"Implementing function body for {spec_display}")
    print(f"Target file: {args.file_path}")
    if args.dry_run:
        print("DRY RUN MODE - no changes will be made")
    
    # Acquire lock to prevent overlapping runs
    if not args.dry_run:
        if not acquire_lock():
            sys.exit(1)
    
    try:
        # 1. Check lock files
        print("1. Checking lock files...")
        if not check_lock_files():
            if not args.dry_run:
                print(
                    "❌ Lock files missing. Please run spec compilation "
                    "first."
                )
                sys.exit(1)
        
        # 2. Assemble Spec slice + stubs + validators
        print("2. Assembling specification context...")
        context = assemble_spec_context(args.spec_id)
        
        if not context["spec"]:
            print(f"❌ Specification {args.spec_id} not found")
            sys.exit(1)
        
        # 3. Prompt the LLM
        print("3. Prompting LLM for implementation...")
        new_body = prompt_llm(context, args.function_name)
        
        # 4. Apply FunctionBodyPatch with AST guard
        print("4. Applying patch with AST guard...")
        if not apply_patch_with_ast_guard(
            args.file_path, 
            args.function_name, 
            new_body,
            args.dry_run
        ):
            print("❌ Failed to apply patch")
            sys.exit(1)
        
        # 5. Run local mypy/tsc + generated tests (skip in dry-run)
        if not args.dry_run:
            print("5. Running validation checks...")
            
            type_check_passed = run_type_checks()
            contract_tests_passed = run_contract_tests(args.spec_id)
            
            # 6. Print succinct pass/fail report
            print("6. Validation Report:")
            type_status = '✅ PASS' if type_check_passed else '❌ FAIL'
            contract_status = (
                '✅ PASS' if contract_tests_passed else '❌ FAIL'
            )
            print(f"   Type checks: {type_status}")
            print(f"   Contract tests: {contract_status}")
            
            if type_check_passed and contract_tests_passed:
                print(
                    "🎉 All checks passed! Function implementation is "
                    "ready."
                )
                sys.exit(0)
            else:
                print(
                    "⚠️ Some checks failed. Please review the "
                    "implementation."
                )
                sys.exit(1)
        else:
            print("5. Skipping validation checks in dry-run mode")
            print("✅ Dry run completed successfully")
    
    finally:
        # Release lock
        if not args.dry_run:
            release_lock()


if __name__ == "__main__":
    main()