#!/usr/bin/env python3
"""
Tests for Web Scraper
Generated by Native DeepCode
"""

from unittest.mock import Mock, patch

import pytest

from src.capabilities.web_scraper import WebScraper, create_scraper


class TestWebScraper:
    """Test suite for WebScraper"""
    
    def test_scraper_creation(self):
        """Test scraper instance creation"""
        scraper = create_scraper()
        assert isinstance(scraper, WebScraper)
        assert scraper.base_url is None
        
        scraper_with_base = create_scraper("https://example.com")
        assert scraper_with_base.base_url == "https://example.com"
    
    @patch('requests.Session.get')
    def test_scrape_page_success(self, mock_get):
        """Test successful page scraping"""
        # Mock response
        mock_response = Mock()
        mock_response.content = b'<html><head><title>Test</title></head><body><h1>Header</h1></body></html>'
        mock_response.raise_for_status.return_value = None
        mock_get.return_value = mock_response
        
        scraper = WebScraper()
        result = scraper.scrape_page("https://test.com")
        
        assert result['title'] == 'Test'
        assert 'Header' in result['headings']
        assert 'error' not in result
    
    @patch('requests.Session.get')
    def test_scrape_page_error(self, mock_get):
        """Test error handling in page scraping"""
        mock_get.side_effect = Exception("Network error")
        
        scraper = WebScraper()
        result = scraper.scrape_page("https://test.com")
        
        assert 'error' in result
        assert result['error'] == "Network error"
    
    def test_scrape_multiple(self):
        """Test scraping multiple URLs"""
        scraper = WebScraper()
        
        with patch.object(scraper, 'scrape_page') as mock_scrape:
            mock_scrape.return_value = {'title': 'Test', 'content': 'data'}
            
            urls = ["https://test1.com", "https://test2.com"]
            results = scraper.scrape_multiple(urls)
            
            assert len(results) == 2
            assert all('url' in result for result in results)
            assert results[0]['url'] == "https://test1.com"


if __name__ == "__main__":
    pytest.main([__file__])
