# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: consensus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "consensus.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0f\x63onsensus.proto\x12\tconsensus"\xa9\x01\n\x10\x43onsensusRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x13\n\x0bnum_samples\x18\x03 \x01(\x05\x12\x13\n\x0btemperature\x18\x04 \x01(\x01\x12\x12\n\nmax_tokens\x18\x05 \x01(\x05\x12\x1c\n\x14\x63onfidence_threshold\x18\x06 \x01(\x01\x12\x19\n\x11temperature_range\x18\x07 \x01(\x01"\xeb\x01\n\x11\x43onsensusResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\x13\n\x0bmethod_used\x18\x03 \x01(\t\x12\x15\n\rraw_responses\x18\x04 \x03(\t\x12M\n\x11\x63onfidence_scores\x18\x05 \x03(\x0b\x32\x32.consensus.ConsensusResponse.ConfidenceScoresEntry\x1a\x37\n\x15\x43onfidenceScoresEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x32]\n\x10\x43onsensusService\x12I\n\x0cGetConsensus\x12\x1b.consensus.ConsensusRequest\x1a\x1c.consensus.ConsensusResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "consensus_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CONSENSUSRESPONSE_CONFIDENCESCORESENTRY"]._loaded_options = None
    _globals["_CONSENSUSRESPONSE_CONFIDENCESCORESENTRY"]._serialized_options = b"8\001"
    _globals["_CONSENSUSREQUEST"]._serialized_start = 31
    _globals["_CONSENSUSREQUEST"]._serialized_end = 200
    _globals["_CONSENSUSRESPONSE"]._serialized_start = 203
    _globals["_CONSENSUSRESPONSE"]._serialized_end = 438
    _globals["_CONSENSUSRESPONSE_CONFIDENCESCORESENTRY"]._serialized_start = 383
    _globals["_CONSENSUSRESPONSE_CONFIDENCESCORESENTRY"]._serialized_end = 438
    _globals["_CONSENSUSSERVICE"]._serialized_start = 440
    _globals["_CONSENSUSSERVICE"]._serialized_end = 533
# @@protoc_insertion_point(module_scope)
