"""Generate chunk manifests for repository Python files.

This script discovers Python modules under ``src/`` and ``tests/`` and groups
them into chunk manifests that respect ``AGENTS.md`` scope boundaries.  Each
manifest lists the Python files associated with a top-level directory (for
example ``src/core`` or ``tests/runtime``) and is written to the ``chunks``
directory.

Usage:
    python tools/chunk_repo.py

The output directory can be customised via ``--output-dir`` and the script can
run in dry-run mode with ``--dry-run`` to preview the manifests without writing
to disk.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Mapping


REPO_ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class ChunkEntry:
    """Representation of a chunk manifest."""

    scope: str
    files: list[Path]


def find_agent_directories(repo_root: Path) -> set[Path]:
    """Return directories that declare ``AGENTS.md`` instructions."""

    return {path.parent for path in repo_root.rglob("AGENTS.md")}


def iter_python_files(base_dirs: Iterable[str]) -> Iterable[Path]:
    """Yield Python files from the provided repository-relative directories."""

    for directory in base_dirs:
        base_path = REPO_ROOT / directory
        if not base_path.exists():
            continue
        for path in base_path.rglob("*.py"):
            if path.is_file():
                yield path


def governing_scope(path: Path, agent_dirs: set[Path]) -> Path:
    """Return the nearest ancestor directory that defines ``AGENTS.md``."""

    for parent in (path,) + tuple(path.parents):
        if parent in agent_dirs:
            return parent
    return REPO_ROOT


def chunk_key_for(file_path: Path, agent_dirs: set[Path]) -> tuple[str, ...]:
    """Compute a stable chunk key for ``file_path`` respecting agent scopes."""

    relative = file_path.relative_to(REPO_ROOT)
    parts = relative.parts
    root = parts[0]

    if len(parts) == 1:
        return (root,)

    top_level = parts[1]
    if top_level.endswith(".py"):
        # File resides directly under the root directory (e.g. ``src/main.py``)
        return (root,)

    scope_dir = governing_scope(file_path.parent, agent_dirs)
    if scope_dir != REPO_ROOT:
        scope_parts = scope_dir.relative_to(REPO_ROOT).parts
        if len(scope_parts) >= 2:
            # Scope aligns with a top-level directory (e.g. ``src/core``)
            if (scope_parts[0], scope_parts[1]) != (root, top_level):
                msg = (
                    "AGENTS.md scope mismatch: file %s is in %s but governed by %s"
                    % (relative.as_posix(), f"{root}/{top_level}", "/".join(scope_parts))
                )
                raise ValueError(msg)
        elif scope_parts and scope_parts[0] != root:
            msg = (
                "AGENTS.md scope for file %s does not align with root directory"
                % relative.as_posix()
            )
            raise ValueError(msg)

    return (root, top_level)


def render_chunk_name(chunk_key: tuple[str, ...]) -> str:
    """Convert a chunk key into an output file name."""

    if not chunk_key:
        raise ValueError("Chunk key cannot be empty")

    if len(chunk_key) == 1:
        return chunk_key[0]

    root, top_level = chunk_key[0], chunk_key[1]
    if root == "src":
        return top_level
    return "-".join(chunk_key)


def build_chunks(agent_dirs: set[Path]) -> Mapping[tuple[str, ...], list[Path]]:
    """Group repository Python files into chunk manifests."""

    chunked: dict[tuple[str, ...], list[Path]] = defaultdict(list)
    for file_path in iter_python_files(["src", "tests"]):
        chunk_key = chunk_key_for(file_path, agent_dirs)
        chunked[chunk_key].append(file_path.relative_to(REPO_ROOT))

    for files in chunked.values():
        files.sort()

    return chunked


def write_chunks(
    chunks: Mapping[tuple[str, ...], list[Path]],
    output_dir: Path,
    dry_run: bool = False,
) -> list[ChunkEntry]:
    """Persist chunk manifests to ``output_dir`` or preview them in dry-run mode."""

    written: list[ChunkEntry] = []

    for chunk_key, files in sorted(chunks.items()):
        name = render_chunk_name(chunk_key)
        chunk_path = output_dir / f"{name}.txt"
        content_lines = [
            "# Auto-generated by tools/chunk_repo.py",
            f"# Scope: {'/'.join(chunk_key)}",
            "",
            *[path.as_posix() for path in files],
        ]
        entry = ChunkEntry(scope="/".join(chunk_key), files=list(files))
        written.append(entry)

        if dry_run:
            continue

        output_dir.mkdir(parents=True, exist_ok=True)
        chunk_path.write_text("\n".join(content_lines) + "\n", encoding="utf-8")

    return written


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=REPO_ROOT / "chunks",
        help="Directory where chunk manifests will be written",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="List the generated chunks without writing files",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    agent_dirs = find_agent_directories(REPO_ROOT)
    chunks = build_chunks(agent_dirs)
    entries = write_chunks(chunks, args.output_dir, dry_run=args.dry_run)

    for entry in entries:
        print(f"Generated chunk {entry.scope} ({len(entry.files)} files)")


if __name__ == "__main__":
    main()
